---
title: "Untitled"
author: "Jacob Hillman"
date: "2025-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#######################################
# Load the packages and read the data #
#######################################

#rm(list=ls()) # Clear objects in the working space.
par.original <- par(no.readonly=TRUE); # Remember the orginal plotting parameters.

library(survival)
library(cluster)
library(protoclust)
library("readxl")


#source("C:/Users/wangh/OneDrive/Works/USU Internship/2022-05 Lymphoma 3/functions.R")

source("functions.R") # already put it in current working directory

#setwd("C:/Users/wangh/OneDrive/Works/USU Internship/2021-06 Lymphoma 2/gehan_minimax")
```


```{r}
#rawdata<-read.csv("pancreas_all_vbl.csv")
rawdata<-read.csv("overall.csv")
```


```{r}
#rawdata<-read.csv("kidney_all_vbl.csv")

names(rawdata)<-c("id","time","site_specific","delta","7T","7N","7M","7M16","7T16","7N16","8T","8N","8M","year","H_C")

rawdata<-rawdata[rawdata$year>=2010 & rawdata$year<=2017,]
```


```{r}
data<-rawdata
```

```{r}
pacman::p_load(tidyverse)
```

```{r}
#unique(data$"H_BG")
```

```{r}
#table(data$H)["8246/3: Neuroendocrine carcinoma, NOS"]
#table(data$H)[""]
```


```{r}
unique(data$"7T")
```
```{r}
unique(data$"8T")
```


```{r}

```



```{r}
# creating T variable
valid_T<-c("T1","T2","T3","T4")

data_T<-data%>%
  mutate(
     T= case_when(
       #`8T`=="T1a"~"T1", # theoretically if I'm doing the analysis on neuroendocrine, T1a,T1b,T1c should not be
       #`8T`=="T1b"~"T1", # used in the creation of my T-variable, if doing exocrine, should be included.
       #`8T`=="T1c"~"T1",
       `8T`=="T1"~"T1",
       `8T`=="T2a"~"T2",
       `8T`=="T2b"~"T2",
       `8T`=="T2"~"T2",
       `8T`=="T3a"~"T3",
       `8T`=="T3b"~"T3",
       `8T`=="T3c"~"T3",
       `8T`=="T3"~"T3",
       `8T`=="T4"~"T4",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T1a"~"T1",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T1b"~"T1",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T1c"~"T1",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T1"~"T1",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T1NOS"~"T1",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T2a"~"T2",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T2b"~"T2",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T2"~"T2",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T2NOS"~"T2",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3a"~"T3",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3b"~"T3",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3c"~"T3",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3"~"T3",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3NOS"~"T3",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T4"~"T4",
       !(`8T`%in% c("T1a","T1b","T2a","T2b","T3a","T3b","T3c","T4","T1","T2","T3")) & `7T` == "T3"~"T3",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="p1"~"T1",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="c1"~"T1",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="p2"~"T2",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="c2"~"T2",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="c3"~"T3",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="p3"~"T3",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="c4"~"T4",
       !(`8T`%in% valid_T) & !(`7T` %in% valid_T) & `7T16`=="p4"~"T4",
       
       
      
     )      )

table(data_T$T)
```



```{r}
# checking that every value of 6T has a corresponding value of 7T
#data_filt<-data%>%
  #filter(data$`7T`=="Blank(s)" & data$`6T` != "Blank(s)")
```


```{r}
#data_filt2<-data%>%
  #filter(data$`7N`=="Blank(s)" & data$`6N` != "Blank(s)")
```

```{r}

```


```{r}
table(data$`7N`)
```

```{r}
# Only N0 and N1 are valid N-values in AJCC 7th or 8th edition
table(data$`8N`)
```



```{r}
# creating N variable

data_TN<-data_T%>%
  mutate(
     N= case_when(
       `8N`=="N1"~"N1",
       `8N`=="N0"~"N0",
       !(`8N` %in% c("N1","N0")) & `7N`=="N1"~"N1",
       !(`8N` %in% c("N1","N0")) & `7N`=="N0"~"N0",
       !(`8N` %in% c("N1","N0")) & !(`7N` %in% c("N1","N0")) & `7N16`=="c0"~"N0",
       !(`8N` %in% c("N1","N0")) & !(`7N` %in% c("N1","N0")) & `7N16`=="p0"~"N0",
       !(`8N` %in% c("N1","N0")) & !(`7N` %in% c("N1","N0")) & `7N16`=="c1"~"N1",
       !(`8N` %in% c("N1","N0")) & !(`7N` %in% c("N1","N0")) & `7N16`=="p1"~"N1",
     )
     
  )
table(data_TN$`N`)
```

```{r}
print(table(data$`7M`))
print(table(data$`8M`))
```


```{r}
#creating M variable

data_TNM = data_TN%>%
  mutate( 
    M= case_when(
      `8M`=="M1"~"M1",
       `8M`=="M0"~"M0",
       !(`8M` %in% c("M1","M0")) & `7M`=="M1"~"M1",
       !(`8M` %in% c("M1","M0")) & `7M`=="M0"~"M0",
       !(`8M` %in% c("M1","M0")) & !(`7M` %in% c("M1","M0")) & `7M16`=="c0"~"M0",
       !(`8M` %in% c("M1","M0")) & !(`7M` %in% c("M1","M0")) & `7M16`=="c1"~"M1",
       !(`8M` %in% c("M1","M0")) & !(`7M` %in% c("M1","M0")) & `7M16`=="p1"~"M1",
      
    )
  )
print(table(data_TNM$`M`))
```


```{r}
```


```{r}
choose_time<-function(data_TNM){
  newdata<-data_TNM[data_TNM$time!= "Unknown",]
  return(newdata)}
data_TNM<-choose_time(data_TNM)

nrow(data_TNM)
```

```{r}
#
# 
print(unique(data_TNM$delta))

data_TNM<-data_TNM%>%
  mutate(delta = case_when(
    delta == "Alive"~"0",
    delta == "Dead"~"1" ) )%>%
  filter(delta %in% c("0","1"))
print(unique(data_TNM$delta))
nrow(data_TNM)
           
           
```

```{r}

```




```{r}
# Choose for "T"
choose_T<-function(data_TNM){
  newdata<- data_TNM[data_TNM$T%in%c("T1",
                             "T2",
                             "T3",
                             "T4"
                             )  ,]
  return(newdata)}
data_TNM<-choose_T(data_TNM)
table(data_TNM$T)
```

```{r}
data_TNM$T<-factor(data_TNM$T,levels=c("T1",
                               "T2",
                               "T3",
                               "T4"))

table(data_TNM$T)
```


```{r}
# Choose for "N"
choose_N<-function(data_TNM){
  newdata<- data_TNM[data_TNM$N%in%c("N0",
                             "N1"
                             
                             )  ,]
  return(newdata)}
data_TNM<-choose_N(data_TNM)
table(data_TNM$N)
```

```{r}
data_TNM$N<-factor(data_TNM$N,levels=c("N0",
                               "N1"
                               ))

table(data_TNM$N)
```

```{r}
# Choose for "M"
choose_M<-function(data_TNM){
  newdata<- data_TNM[data_TNM$M%in%c("M0",
                             "M1"
                             
                             )  ,]
  return(newdata)}
data_TNM<-choose_M(data_TNM)
table(data_TNM$M)
```

```{r}
data_TNM$M<-factor(data_TNM$M,levels=c("M0",
                               "M1"
                               ))

table(data_TNM$M)
```

```{r}
# Choose for "Histology"
choose_H<-function(data_TNM){
  #newdata<- data_TNM[data_TNM$H_BG != "8000-8009: unspecified neoplasms" & data_TNM$H_BG != "8140-8389: adenomas and adenocarcinomas",]
  neuro_codes <- c("8150", "8151", "8152", "8153", "8155", "8156", "8158", "8240", "8249")
  newdata <- data_TNM[data_TNM$H_C %in% neuro_codes, ]

   #newdata<- data_TNM[data_TNM$H_C == "8150" & data_TNM$H_C == "8151" &  data_TNM$H_C == "8152" & data_TNM$H_C == "8153" & data_TNM$H_C == "8154" & data_TNM$H_C == "8155" & data_TNM$H_C == "8156" & data_TNM$H_C == "8158" & data_TNM$H_C == "8240" & data_TNM$H_C == "8249" ,]
  return(newdata)}
data_TNM<-choose_H(data_TNM)
table(data_TNM$H_C)
```


```{r}
table(data_TNM$H)
```


```{r}

```

```{r}
table(data_TNM$T)
table(data_TNM$N)
table(data_TNM$M)
table(data_TNM$S)

```

```{r}
round(100*table(data_TNM$S)/nrow(data_TNM),1)
round(100*table(data_TNM$T)/nrow(data_TNM),1)
round(100*table(data_TNM$N)/nrow(data_TNM),1)
round(100*table(data_TNM$M)/nrow(data_TNM),1)

```
```{r}

```


```{r}
########################################################
#################    Don't Change   ######################
vars<-c("T","N","M")   # Construct a vector "vars" that contains the name of the factors we are interested in. The names must be exact the same as the factor names in the inputted data.
##############################################################
#############################################################
```

```{r}
elimSize<-0  # set a number "elimSize" so that any combination with size < "elimSize" will be eliminated.

displayFinalKM<-1 # 1--display survival curves of "boxes"; 0--don't display
#w<-120 # Set the study time by months

varIndex=match(vars,names(data_TNM)) #Find the index of positions of variables
numVar<-length(varIndex) #Count the number of variables
```

```{r}
mydata=cbind.data.frame(data_TNM[,varIndex],time=data_TNM$time,delta=data_TNM$delta)  # Keep only "time", "delta" and interested factors.
```

```{r}
data=data_TNM
```


```{r}
data_dead<-data_TNM%>%
  filter(delta==1)
nrow(data_dead)
```

```{r}

```


```{r}
# "Count" is a variable that counts number of observation for each combination.

#314391
```

```{r}
######################
# Set the parameters #
######################

linkage<-"minimax" # Choose a linkage method
#vars<-c("S","I","T","A","X")    # Construct a vector "vars" that contains the name of the factors we are interested in. The names must be exact the same as the factor names in the inputted data.
vars<-c("T","N","M")    # Construct a vector "vars" that contains the name of the factors we are interested in. The names must be exact the same as the factor names in the inputted data.


elimSize<-0  # set a number "elimSize" so that any combination with size < "elimSize" will be eliminated.
finalGroups<-0 # Set the number of clusters in the final results (1 < "finalGroups" < total number of combinations (with size smaller than "elimSize") ) If 0 is input, then the number of groups will be decided by C-index
displayFinalKM<-1 # 1--display survival curves of "boxes"; 0--don't display
w<-60 # Set the study time by months
#w<-max(mydata$time)

varIndex=match(vars,names(data)) #Find the index of positions of variables
numVar<-length(varIndex) #Count the number of variables



```

```{r}
print(varIndex)
ncol(data_TNM)
names(data_TNM)[32:34]

```

```{r}
  # Keep only "time", "delta" and interested factors.
mydata=cbind.data.frame(data[,varIndex],time=data$time,delta=data$delta)  
# Add a column "comb" to "mydata" to indicate the combinations (the reason of using if-else syntax is that "paste" function has to be used with at least two variables.)
if(numVar==1){
  comb<-data[vars]
  mydata<-cbind.data.frame(mydata,comb)
  colnames(mydata)[1]<-"comb"
}else{
  mydata$comb<-apply(data_TNM[,varIndex],1,paste,collapse="") 
}


mydata<-cbind(H=data$H,mydata) # when and if I add age, add argument data$A here

# "Count" is a variable that counts number of observation for each combination.
Count<-aggregate(count ~ comb, cbind(count=1,mydata),length)

# Names of Combinations with size > elimSize will be recorded in the variable "restcomb"
restcomb<-Count[Count$count>=elimSize,]$comb

# Count how many different combinations left.
numComb<-length(restcomb)

# Construct a "testdata" that only keeps combinations in "restcomb"
testdata=mydata[mydata$comb %in% restcomb,]

# Add a column "comb_int" to represent the index of "comb" in the "restcomb" for each observation (in alphabeta order).
testdata$comb_ind<-as.integer(factor(testdata$comb))

nrow(testdata)
#160083
##################################################################################

```

```{r}
testdata$time<-as.numeric(testdata$time)
testdata$delta<-as.numeric(testdata$delta)

```



```{r}
# create data groups for each survival curve

mydata_old_stage = testdata%>%
  mutate(old_stage = case_when(comb=="T1N0M0"~1,
                               comb == "T2N0M0" | comb == "T3N0M0"~2,
                               comb == "T4N0M0" | comb == "T1N1M0" | comb == "T2N1M0" | comb == "T3N1M0"|comb == "T4N1M0"~3,
                               M == "M1"~4))
```


```{r}
# to get chunk below to work change chunk above to assign numerical 1 2 3 4 instead of "Stage1" "Stage2" etc...
```


```{r}
library(compareC)
compareC(mydata_old_stage$time, mydata_old_stage$delta, -mydata_old_stage$old_stage, -mydata_old_stage$old_stage)
```



```{r}
stage1<-mydata_old_stage%>%
  filter(old_stage=="Stage1")
nstage1<-as.numeric(nrow(stage1))
stage2<-mydata_old_stage%>%
  filter(old_stage=="Stage2")
nstage2<-as.numeric(nrow(stage2))
stage3<-mydata_old_stage%>%
  filter(old_stage=="Stage3")
nstage3<-as.numeric(nrow(stage3))
stage4<-mydata_old_stage%>%
  filter(old_stage=="Stage4")
nstage4<-as.numeric(nrow(stage4))
stage_sizes<-c(nstage1,nstage2,nstage3,nstage4)
print(stage_sizes)

invalid_stages <- mydata_old_stage %>%
  filter(!(old_stage %in% c("Stage1", "Stage2", "Stage3", "Stage4")))

print(invalid_stages)


deaths<-c()
for (i in 1:4){
  stage<-get(paste0("stage",i))
  nstage<-get(paste0("nstage",i))
  stage_alive<-stage%>%
    mutate(time = as.numeric(time)) %>%
    filter(time>60)
  stage_n_alive<-nrow(stage_alive)
  deaths_num<-(nstage-stage_n_alive)
  deaths[[i]]<-deaths_num
}
print(deaths)
```


```{r}
levels(factor(mydata_old_stage$old_stage))
legend_labs<-levels(factor(mydata_old_stage$old_stage))
length(legend_labs)
```


```{r}
mydata_old_stage$time<-as.numeric(mydata_old_stage$time)
mydata_old_stage$delta<-as.numeric(mydata_old_stage$delta)




grouptest<-survfit(Surv(time,delta)~old_stage, data=mydata_old_stage)

numerals = c("I","II","III","IV")
#for(i in 1:length(stage_sizes)){
for (i in seq_along(numerals)){
  #legend_labs[i]<-paste("Group",i," n=",stage_sizes[i]," percent=",percentages[i],sep="")}
  legend_labs[i]<-paste("Stage ",numerals[i]," n=",stage_sizes[i],sep="")}
  #legend_labs[i] <- paste0("Group ", i, " n=", stage_sizes[i], " (deaths=", deaths[i], ")")}

plot(grouptest,ylim=c(0, 1.0),
     
     xlim=c(0,60),
     xlab=("Survival Time by Months"),
     ylab=("Proportion Surviving"),
     cex=1,
     cex.lab=1.5,
     cex.axis=1.5,
     col=c("gray50","cyan3","orange" , 6,  3, 2, 4, 9),
     lwd=3.0,
     lty=1,
     mark.time=FALSE)
title(main = "")
legend("bottomleft",
       legend=legend_labs,
       col=c("gray50","cyan3","orange" , 6,  3, 2, 4, 9),
       cex=1,
       lty=1,
       lwd=3.0,
       xjust=1, yjust=1)


```

```{r}
# get c-index from AJCC method being used above
# Define a function "Esurv_c" to calculated estimated survival time.
# Define a function "Esurv_c" to calculated estimated survival time.
Esurv_c<-function(data,maxt){
  surv<-KMsurv(data)
  if(maxt<surv[nrow(surv),1]){stop("overall_maxt < maxt")}
  Es<-surv[1,1]*1
  if(nrow(surv)>1){
    for(i in 1:(nrow(surv)-1)){
      Es<-sum(Es,surv[i,2]*(surv[i+1,1]-surv[i,1]))
    }
  }
  # Add the part after the last death
  Es<-sum(Es,surv[nrow(surv),2]*(maxt-surv[nrow(surv),1]))
  return(Es)
}

```


```{r}
 # Define a function C_index with an arguments "data" to calculate Harrell's C-index. "data" has 3 columns "time", "delta" and "E_T".
  C_index<-function(data){
    
    # Aggregate the rows in data by adding a column "count"
    data <- aggregate(count ~ ., cbind(count=1,data),length) 
    
    # Sort the data by order of time (ascending) and delta (descending)
    ord <- order(data[,1], -data[,2]) 
    data <- as.matrix(data[ord,])
    
    # Find the row positions of deaths. Minus 1 as the index of element in C starts at 0 instead of 1
    di <- which(data[,2] == 1)-1
    
    library(Rcpp) # Call "Rcpp" package to use C function
    cppFunction('NumericVector Cindex(NumericMatrix data,NumericVector di){ 
                int nrow = data.nrow();
                int ndi = di.size();
                double numerator = 0;
                double denominator = 0;
                NumericVector out(2);
                
                int ii = 0;
                int i = di[ii];
                
                NumericVector f(3);
                NumericVector g(3);
                
                while(ii<ndi){
                if(i==(nrow-1)){break;}
                
                for (int j=i+1;j<nrow;j++){
                int count = data(i,3)*data(j,3);
                
                if (data(j,0) > data(i,0)) {
                denominator += count;
                if (data(j,2) > data(i,2))
                {numerator += count; }
                else if (data(j,2) == data(i,2)) 
                {numerator += 0.5*count; }
                
                }else{
                if (data(j,1)==0){
                denominator += count;
                if (data(j,2) > data(i,2)) {
                numerator += count;}
                else if (data(j,2) == data(i,2)) 
                {numerator += 0.5*count;}
                }
                }
                }
                i = di[++ii];
                }
                out[0]=numerator;
                out[1]=denominator;
                return out;
  }
                ')
    result<-Cindex(data,di)
    return(result[[1]]/result[[2]])
  }

  
```

```{r}
# tempassign<-as.list(unique(mydata_old_stage$old_stage)) # Starting with leaves' order in the dendrogram, construct a list "tempassign" temporarily recording combinations' order in the dendrogram
tempassign<-as.list(1:4)
```


```{r}
 # Construct Cindexdata which is used to input in function "C_index"
    Cindexdata<-mydata_old_stage 
    
    # Add a column "group_ind" to record the group number for each case
# Make sure old_stage is consistent (character, not factor)
Cindexdata$old_stage <- as.character(Cindexdata$old_stage)

# Define the unique stages and assign group numbers
stage_levels <- sort(unique(Cindexdata$old_stage))  # Should return: "Stage1" "Stage2" ...
stage_map <- setNames(1:length(stage_levels), stage_levels)

# Convert stage labels to numeric group_ind using the map
Cindexdata$group_ind <- stage_map[Cindexdata$old_stage]
    
    
    maxt<-max(Cindexdata$time)
    # Add a column "E_T" to record the estimated survival time for each case
    Cindexdata$E_T<-0
    for(k in 1:length(tempassign)){
      group_k_data<-Cindexdata[Cindexdata$group_ind==k,c("time","delta")] # group_ind needs to be 1,2,3,or 4
      Cindexdata$E_T[Cindexdata$group_ind==k]<-Esurv_c(group_k_data,maxt)
    }
    
    Cindexdata<-Cindexdata[,c("time","delta","E_T")] # Keep only 3 columns of interest
    
    write.table(Cindexdata, file = "AJCCdata.txt", sep = "\t", row.names = FALSE, quote = FALSE)
    
    allC <- cbind(allC, C_index(Cindexdata)) # Record the C-index in vector "allC"
    
    
    
    C_index(Cindexdata)
```
```{r}
 
```





```{r}


```

```{r}
sapply(Cindexdata, class)

```


```{r}
targets <- c("T1N0M0","T2N0M0","T4N0M0","T1N0M1",
             "T3N0M0","T1N1M0","T2N0M1",
             "T2N1M0","T3N0M1",
             "T3N1M0","T4N0M1",
             "T4N1M0","T1N1M1",
             "T2N1M1",
             "T3N1M1",
             "T4N1M1")
counts <- integer(length(targets))   # empty vector to store counts

for (i in seq_along(targets)) {
  counts[i] <- sum(mydata_old_stage$comb == targets[i])
}

result <- data.frame(TNM_stage = targets,
                     Count = counts)

print(result)
sum(counts)
```




```{r}
plot(
  grouptest,
  ylim = c(0, 1.0),
  xlim = c(0, 60),
  xlab = "Survival Time by Months",
  ylab = "Proportion Surviving",
  cex = 1,
  cex.lab = 1.5,
  cex.axis = 1.5,
  col = c("gray50","cyan3","orange", 6, 3, 2, 4, 9),
  lwd = 3.0,
  lty = 1,
  mark.time = FALSE,
  axes = FALSE,     # <-- stop plot.survfit() from drawing axes
  yaxs = "i"        # <-- avoid automatic y-range expansion
)

## draw axes manually
axis(1, cex.axis = 1.5)                                    # x-axis (default ticks)
axis(2, at = seq(0, 1, by = 0.2), las = 1, cex.axis = 1.5)  # y-axis ticks at 0.2 steps
box()                                                      # redraw the plot border

title(main = "")
legend(
  "bottomleft",
  legend = legend_labs,
  col = c("gray50","cyan3","orange", 6, 3, 2, 4, 9),
  cex = 1,
  lty = 1,
  lwd = 3.0,
  xjust = 1,
  yjust = 1
)

```


```{r}
old_stage_stages_1_and_2<-mydata_old_stage%>%
  filter(old_stage==1|old_stage==2)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_1_and_2)
surv_diff
```

```{r}
old_stage_stages_1_and_3<-mydata_old_stage%>%
  filter(old_stage==1|old_stage==3)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_1_and_3)
surv_diff
```


```{r}
old_stage_stages_1_and_4<-mydata_old_stage%>%
  filter(old_stage==1|old_stage==4)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_1_and_4)
surv_diff
```

```{r}
old_stage_stages_3_and_2<-mydata_old_stage%>%
  filter(old_stage==2|old_stage==3)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_3_and_2)
surv_diff
```

```{r}
old_stage_stages_4_and_2<-mydata_old_stage%>%
  filter(old_stage==4|old_stage==2)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_4_and_2)
surv_diff
```

```{r}
old_stage_stages_4_and_3<-mydata_old_stage%>%
  filter(old_stage==4|old_stage==3)
surv_diff <- survdiff(Surv(time, delta) ~ old_stage, data = old_stage_stages_4_and_3)
surv_diff
```







